// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float3> Result;

float offsetInY;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    Result[0].y = Result[0].y + offsetInY;
    
    //float3 position = Result[0];
    //position.y = position.y + offsetInY;
    //Result[0] = position;

}
